### ISSUE TITLE
linux下保存文件存在问题

### ISSUE THREAD

**Issue by kN6jq** [i11us0ry/AScan#1]
![image](https://user-images.githubusercontent.com/27048404/173730042-9ec55112-267f-4b72-ad93-6c91ae5393ba.png)

**Comment by i11us0ry** [comment]
因为之前只想过win下运行情况所以没做linux的一些适配，导致输出文件有问题，现在新上传的是做了适配的，我本地跑了也没问题，你那边试试看呢
