### ISSUE TITLE
[Error] 请求发生错误，5秒后重试 Get "https://aiqicha.baidu.com/detail/icpinfoAjax?size=100&pid=25287101280058": EOF [Error] 请求发生错误，5秒后重试

### ISSUE THREAD

**Issue by s7safe** [i11us0ry/AScan#4]
[Error] 请求发生错误，5秒后重试
Get "https://aiqicha.baidu.com/detail/icpinfoAjax?size=100&pid=25287101280058": EOF
[Error] 请求发生错误，5秒后重试

**Comment by i11us0ry** [comment]
cookie是会员的吗？这种报错之前测试发生在非会员或多脚本同时进行的情况，如果都不是，方便的话可以拿关键字私我下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 下午4:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/AScan] [Error] 请求发生错误，5秒后重试 Get "https://aiqicha.baidu.com/detail/icpinfoAjax?size=100&amp;pid=25287101280058": EOF [Error] 请求发生错误，5秒后重试 (Issue #4)




 
[Error] 请求发生错误，5秒后重试
 Get "https://aiqicha.baidu.com/detail/icpinfoAjax?size=100&amp;pid=25287101280058": EOF
 [Error] 请求发生错误，5秒后重试

**Comment by s7safe** [comment]
不是会员，之前用的好好的，关键字为字节跳动 运行命令“.\main.exe -n 字节跳动 -s -b”

**Comment by s7safe** [comment]
![图片](https://user-images.githubusercontent.com/54035968/229344978-c65c9853-e635-4905-bfa1-e6faa893c944.png)

**Comment by i11us0ry** [comment]
昂，接口更新了貌似



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [i11us0ry/AScan] [Error] 请求发生错误，5秒后重试 Get "https://aiqicha.baidu.com/detail/icpinfoAjax?size=100&amp;pid=25287101280058": EOF [Error] 请求发生错误，5秒后重试 (Issue #4)

**Comment by i11us0ry** [comment]
更新了，再试试呢

**Comment by s7safe** [comment]
好了好了，感谢
